"""message

Revision ID: 94723ac39f33
Revises: 6a3adc38c1a0
Create Date: 2025-01-28 10:22:13.518025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94723ac39f33'
down_revision = '6a3adc38c1a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
